name: Full Build

permissions:
  contents: write

on:
  push:
    branches: [ master ]
    tags: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get tag number from tag string
        id: tag_number
        if: ${{ startsWith( github.ref, 'refs/tags/' ) }}
        run: |
          orig_tag="${{ github.ref_name }}"
          echo "tag_number=${orig_tag/v/}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master
          path: master

      - name: Setup MAPI
        uses: BadMagic100/setup-hk@v2
        with:
          apiPath: HkRefs
          dependencyFilePath: master/ModDependencies.txt

      - name: Install dependencies master
        run: dotnet restore
        shell: bash
        working-directory: master

      - name: Build master
        run: dotnet build -c Release /p:AssemblyVersion=${{ steps.tag_number.outputs.tag_number }}
        shell: bash
        working-directory: master

      - name: Prepare master artifacts for release
        uses: christopherhx/gitea-upload-artifact@v4
        with:
          name: Publish-Master
          path: master/bin/Publish

  release:
    if: ${{ startsWith( github.ref, 'refs/tags/' ) }}
    needs:
      - build

    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: christopherhx/gitea-download-artifact@v4
        with:
          path: artifacts

      - name: Get build details
        id: details
        # this assumes that an MSBuild task that writes the SHA256 of the zip file to SHA.txt, and the mod version (usually
        # the same as the assembly version) to version.txt. The contents of these files are read to step outputs for use in release
        run: |
          sha="$(sed '4q;d' artifacts/Publish-Master/Core_FsmUtil/SHA.txt)"
          ver="${{ github.ref_name }}"
          echo "archiveHash=$sha" >> $GITHUB_OUTPUT
          echo "buildVersion=$ver" >> $GITHUB_OUTPUT
        shell: bash

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          generate_release_notes: true
          fail_on_unmatched_files: true
          tag_name: ${{ steps.details.outputs.buildVersion }}
          body: |
            SHA256 of Core_FsmUtil.zip: ${{ steps.details.outputs.archiveHash }}  
            Attachments:  
            - Core_FsmUtil.zip
              - to be used for the ModInstaller
            - Core_FsmUtil.dll
              - the mod, also inside Core_FsmUtil.zip
          files: |
            artifacts/Publish-Master/Core_FsmUtil/Core_FsmUtil.zip
            artifacts/Publish-Master/Core_FsmUtil/Core_FsmUtil.dll
